/*
 * Decompiled with CFR 0.152.
 */
/*
 * Duplicate member names - consider using --renamedupmembers true
 */
public interface k {
    public static final int F = 640;
    public static final int G = 360;
    public static final int H = (360 >> 1) - 10;
    public static final int[] b = new int[]{0, 1, 2, 3, 4, 5, 6, 7};
    public static final int[] c = new int[]{65, 83, 73, 84, 74, 65};
    public static final int[] d = new int[]{1, 3, 0, 6, 5, 4, 7, 2};
    public static final int I = F - 20;
    public static final int J = G - 10;
    public static final int K = F / 2;
    public static final int L = 9 * G / 10 + 20;
    public static final int M = F - 20;
    public static final int N = F / 2 - 10;
    public static final int O = G - 22;
    public static final int P = F - 50;
    public static final int Q = F - 48 + 22;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int ar;
    public static final int as;
    public static final int at;
    public static final int au;
    public static final int av;
    public static final int aw;
    public static final int ax;
    public static final int ay;
    public static final int az;
    public static final int aA;
    public static final int aB;
    public static final int aC;
    public static final int aD;
    public static final int aE;
    public static final int aF;
    public static final int aG;
    public static final int aH;
    public static final int aI;
    public static final int aJ;
    public static final int aK;
    public static final int aL;
    public static final int aM;
    public static final int aN;
    public static final int aO;
    public static final int aP;
    public static final int aQ;
    public static final int aR;
    public static final int aS;
    public static final int aT;
    public static final int aU;
    public static final int aV;
    public static final int aW;
    public static final int aX;
    public static final int aY;
    public static final int aZ;
    public static final int ba;
    public static final int bb;
    public static final int bc;
    public static final int bd;
    public static final int be;
    public static final int bf;
    public static final int bg;
    public static final int bh;
    public static final int bi;
    public static final int bj;
    public static final int bk;
    public static final int bl;
    public static final int bm;
    public static final int bn;
    public static final int bo;
    public static final int bp;
    public static final int bq;
    public static final int br;
    public static final int bs;
    public static final int bt;
    public static final int bu;
    public static final int bv;
    public static final int bw;
    public static final int bx;
    public static final int by;
    public static final int bz;
    public static final c a;
    public static final byte[] b;
    public static final byte[] c;
    public static final byte[] d;
    public static final byte[] e;
    public static final byte[] f;
    public static final byte[] g;
    public static final byte[] h;
    public static final byte[] i;
    public static final byte[] j;
    public static final byte[] k;
    public static final byte[] l;
    public static final byte[] m;
    public static final byte[] n;
    public static final byte[] o;
    public static final int[] e;
    public static final int[] f;
    public static final int bA;
    public static final int bB;
    public static final int bC;
    public static final int bD;
    public static final int bE;
    public static final int bF;
    public static final int bG;
    public static final int bH;
    public static final int bI;
    public static final int bJ;
    public static final int bK;
    public static final int bL;
    public static final int bM;
    public static final int bN;
    public static final int bO;
    public static final int bP;
    public static final int bQ;

    static {
        S = R = G - 22;
        T = R - 24;
        U = (F - 170) / 2 - 7;
        V = U + 33;
        W = F - 8;
        Y = X = W / 5;
        Z = F / 2;
        aa = G - 115;
        ab = F - 20;
        ac = F / 2;
        ad = (G - 20) / 2;
        ae = ad + 25 - 7;
        af = ad + 25 + 30 - 7;
        ag = ad - 146 + 4;
        ah = ad - 110 + 4 + 30;
        ai = F - 50;
        aj = ad - 146 + 55;
        ak = ad - 110 + 55 + 30;
        al = F - 280;
        am = G - 110 + 18;
        an = ag + 40;
        ao = an + 40;
        ap = ac - 100;
        aq = ac + 83 + 50;
        ar = aq - 42;
        as = aq + 39;
        at = ac;
        au = ae + 85;
        av = ac - 83;
        aw = au + 2;
        ax = av + 2;
        ay = ae + 85;
        az = F / 2 - 100;
        aA = F / 2 - 90;
        aB = ad + 105;
        aC = F - 280;
        aD = (G - 135 >> 1) + 30 + 8;
        aE = F - 20;
        aF = ad - 110;
        aG = aF + 18 + 15;
        aH = F - 8 - 8;
        aI = aF;
        aJ = G - 30;
        aK = ad;
        aL = ad - 20;
        aM = aK + 6 + 13 - 2;
        aN = aK + 19;
        aO = ac - 40;
        aP = aK + 67;
        aQ = aK + 107;
        aR = aK + 87;
        aS = ac - 5;
        aT = aK + 60;
        aU = aK + 98;
        aV = aK + 80;
        aW = ad - 92;
        aX = ad - 40;
        aY = aW + 2;
        aZ = aY + 11 - 2;
        ba = ac - 60;
        bb = G - 90;
        bc = bb + 30;
        be = bd = ad + 25;
        bf = ad - 15;
        bg = ad + 15;
        bh = ac - 55;
        bi = ac + 55;
        bk = bj = ac;
        bl = ac;
        bm = ad + 25;
        bn = bh;
        bo = bi;
        bp = bg;
        bq = bg;
        br = G - 35;
        bs = G;
        bt = F - 10 - 4;
        bu = br + 10;
        bv = F - 34;
        bw = G / 3 << 16;
        bx = 2 * G / 3 << 16;
        by = bx - bw;
        bz = by + 0x1900000;
        a = new c("{");
        b = new byte[]{3, 1, 0, 1, 3, 9, 15, 1, 2};
        c = new byte[]{4, 1, 0, 1, 3, 15, 9, 32, 1, 2};
        d = new byte[]{5, 1, 0, 2, 3, 15, 4, 9, 32, 1, 2, 24};
        e = new byte[]{2, 2, 0, 1, 3, 21, 0, 13, 14};
        f = new byte[]{5, 2, 0, 1, 3, 21, 4, 30, 12, 0, 13, 14};
        g = new byte[]{5, 3, 0, 1, 3, 21, 4, 30, 12, 1, 0, 13, 14};
        h = new byte[]{2, 2, 1, 1, 27, 3, 0, 7, 5, 2};
        i = new byte[]{3, 3, 2, 2, 27, 4, 3, 7, 0, 1, 5, 11, 2, 26};
        j = new byte[]{2, 4, 3, 2, 27, 3, 7, 0, 19, 1, 5, 18, 11, 2, 26};
        k = new byte[]{2, 2, 1, 3, 23, 4, 0, 7, 17, 14, 24, 2};
        l = new byte[]{3, 3, 3, 3, 23, 31, 27, 7, 0, 1, 17, 5, 18, 14, 24, 2};
        m = new byte[]{3, 4, 4, 3, 23, 31, 27, 7, 19, 0, 1, 17, 5, 18, 11, 14, 24, 2};
        n = new byte[]{2, 4, 4, 3, 31, 27, 7, 19, 0, 1, 17, 5, 18, 11, 14, 24, 2};
        o = new byte[]{2, 2, 4, 1, 1, 3, 2, 2, 4, 1, 2, 3, 1, 2, 4, 1, 3, 3, 3, 2, 4, 1, 2, 2, 4, 2, 4, 1, 3, 3, 1, 1, 2};
        e = new int[]{0, 0, 0, 0};
        f = new int[]{0, 0, 0, 0};
        bA = G * 63 / 100;
        bB = G * 47 / 100;
        bC = G * 31 / 100;
        bD = F >> 2;
        bE = G / 4 + 25;
        bF = F - 10;
        bG = bF - 40;
        bH = bE;
        bJ = bI = F / 2;
        bK = G - 40;
        bL = F;
        bM = G - 100;
        bN = F - 50;
        bO = G / 4;
        bP = F / 4;
        bQ = F / 4;
    }
}

